-- Migration: Create pricing_ranges table
CREATE TABLE IF NOT EXISTS pricing_ranges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(16) NOT NULL, -- 'BUYER' or 'VENDOR'
  label VARCHAR(128) NOT NULL,
  min_value VARCHAR(64) NOT NULL,
  max_value VARCHAR(64) NOT NULL,
  description TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
